services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: german_tutor_backend
    restart: always
    env_file: ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
      - ./backend/static:/app/static
      - ./service-account.json:/var/secrets/service-account.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/var/secrets/service-account.json

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: german_tutor_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend # Фронтенд залежить від бекенду
