export const UI_STRINGS = {
    'ukr': {
        'settings': 'Налаштування',
        'library': 'Бібліотека',
        'logout': 'Вийти',
        'generate_new': 'Створити Урок',
        'topic': 'Тема уроку',
        'level': 'Рівень',
        'count': 'Кількість речень',
        'generate_btn': 'Згенерувати',
        'vocab': 'Словник',
        'voice': 'Голос',
        'back': 'Назад',
        'topic_placeholder': 'Наприклад: Подорож, IT, Спорт...',
        'generating': 'Генерація...',
        'error_alert': 'Помилка',
        'show_translation': 'Показати переклад',
        'hide_translation': 'Приховати переклад',
        'play_all': 'ПРОГРАТИ ВСЕ',
        'stop': 'ЗУПИНИТИ',
        'add_translation': '+ ПЕРЕКЛАСТИ',
        'grammar_tooltip': 'Пояснити граматику',
        'lesson_vocab': 'СЛОВНИК УРОКУ',
        'empty_vocab_prompt': 'Виділіть слово в тексті, щоб додати переклад.',
        'quiz_tab': 'Квіз',
        'vocab_tab': 'Словник уроку',
        'check_btn': 'Спробувати',
        'next_btn': 'Далі',
        'done_btn': 'Готово',
        'finish_btn': 'Перевірити',
        'retry_btn': 'Спробувати ще',
        'quiz_completed': 'Квіз завершено!',
        'your_score': 'Твій результат',
        'restart_btn': 'Спочатку',
        'abort_btn': 'Завершити',
        'word_added': 'Слово додано',
        'selection_limited_toast': 'Переклад не більше 4 слів',
        'translation_failed_msg': 'Не вдалося отримати переклад',
        'audio_failed_msg': 'Не вдалося згенерувати аудіо',
        'word_exists': 'Слово вже є у словнику',
        'error_generic': 'Сталася помилка',
        'loading': 'Завантаження...',
        'word_deleted': 'Слово видалено',
        'confirm_delete_word': 'Видалити слово?',
        'restart_confirm_title': 'Почати спочатку?',
        'restart_confirm_msg': 'Поточний прогрес буде втрачено. Ви впевнені?',
        'abort_confirm_title': 'Завершити квіз?',
        'abort_confirm_msg': 'Прогрес не буде збережено. Вийти?',
        'btn_cancel': 'Скасувати',
        'exit_btn': 'Вийти'
    },
    'eng': {
        'settings': 'Settings',
        'library': 'Library',
        'logout': 'Logout',
        'generate_new': 'Create Lesson',
        'topic': 'Lesson Topic',
        'level': 'Level',
        'count': 'Sentence count',
        'generate_btn': 'Generate',
        'vocab': 'Vocabulary',
        'voice': 'Voice',
        'back': 'Back',
        'topic_placeholder': 'E.g.: Travel, IT, Sports...',
        'generating': 'Generating...',
        'error_alert': 'Error',
        'show_translation': 'Show translation',
        'hide_translation': 'Hide translation',
        'play_all': 'PLAY ALL',
        'stop': 'STOP',
        'add_translation': '+ TRANSLATE',
        'grammar_tooltip': 'Explain grammar',
        'lesson_vocab': 'LESSON VOCABULARY',
        'empty_vocab_prompt': 'Highlight a word in the text to add a translation.',
        'quiz_tab': 'Quiz',
        'vocab_tab': 'Lesson Vocabulary',
        'check_btn': 'Try',
        'next_btn': 'Next',
        'finish_btn': 'Check',
        'retry_btn': 'Retry',
        'done_btn': 'Done',
        'quiz_completed': 'Quiz Completed!',
        'your_score': 'Your Score',
        'restart_btn': 'Restart',
        'abort_btn': 'Finish',
        'word_added': 'Word added',
        'selection_limited_toast': 'Translation up to 4 words',
        'translation_failed_msg': 'Failed to get translation',
        'audio_failed_msg': 'Failed to generate audio',
        'word_exists': 'Word already in vocabulary',
        'error_generic': 'An error occurred',
        'loading': 'Loading...',
        'word_deleted': 'Word deleted',
        'confirm_delete_word': 'Delete word?',
        'restart_confirm_title': 'Restart Quiz?',
        'restart_confirm_msg': 'Current progress will be lost. Are you sure?',
        'abort_confirm_title': 'Exit Quiz?',
        'abort_confirm_msg': 'Progress will be lost. Exit?',
        'btn_cancel': 'Cancel',
        'exit_btn': 'Exit'
    }
};

export const getUI = (lang) => UI_STRINGS[lang] || UI_STRINGS['ukr'];