export const UI_STRINGS = {
    'ukr': {
        'settings': 'Налаштування',
        'library': 'Бібліотека',
        'main': 'Головна',
        'logout': 'Вийти',
        'generate_new': 'Створити Урок',
        'topic': 'Тема уроку',
        'level': 'Рівень',
        'count': 'Кількість речень',
        'generate_btn': 'Згенерувати',
        'vocab': 'Словник',
        'voice': 'Голос',
        'back': 'Назад',
        'topic_placeholder': 'Наприклад: Подорож, IT, Спорт...',
        'generating': 'Генерація...',
        'error_alert': 'Помилка',
        'show_translation': 'Показати переклад',
        'hide_translation': 'Приховати переклад',
        'play_all': 'ПРОГРАТИ ВСЕ',
        'stop': 'ЗУПИНИТИ',
        'add_translation': '+ ПЕРЕКЛАСТИ',
        'grammar_tooltip': 'Пояснити граматику',
        'lesson_vocab': 'СЛОВНИК УРОКУ',
        'empty_vocab_prompt': 'Виділіть слово в тексті, щоб додати переклад.',
        'quiz_tab': 'Квіз',
        'vocab_tab': 'Словник уроку',
        'check_btn': 'Спробувати',
        'next_btn': 'Далі',
        'done_btn': 'Готово',
        'finish_btn': 'Перевірити',
        'retry_btn': 'Спробувати ще',
        'quiz_completed': 'Квіз завершено!',
        'your_score': 'Твій результат',
        'restart_btn': 'Спочатку',
        'abort_btn': 'Завершити',
        'word_added': 'Слово додано',
        'selection_limited_toast': 'Переклад не більше 4 слів',
        'translation_failed_msg': 'Не вдалося отримати переклад',
        'audio_failed_msg': 'Не вдалося згенерувати аудіо',
        'word_exists': 'Слово вже є у словнику',
        'error_generic': 'Сталася помилка',
        'loading': 'Завантаження...',
        'word_deleted': 'Слово видалено',
        'confirm_delete_word': 'Видалити слово?',
        'restart_confirm_title': 'Почати спочатку?',
        'confirm_title': 'Підтвердження',
        'confirm_delete_text_msg': 'Ви впевнені, що хочете видалити цей текст?',
        'btn_delete': 'Видалити',
        'restart_confirm_msg': 'Поточний прогрес буде втрачено. Ви впевнені?',
        'abort_confirm_title': 'Завершити квіз?',
        'abort_confirm_msg': 'Прогрес не буде збережено. Вийти?',
        'btn_cancel': 'Скасувати',
        'exit_btn': 'Вийти',
        'my_vocab': 'МІЙ СЛОВНИК',
        'save_settings': 'Зберегти',
        'interface_lang': 'Мова інтерфейсу',
        'my_texts': 'Мої тексти',
        'read': 'Читати',
        'settings_saved': 'Налаштування збережено',
        'style_label': 'Стиль тексту',
        'style_neutral': 'Нейтральний',
        'style_formal': 'Офіційний',
        'style_conversational': 'Розмовний',
        'style_dialogue_informal': 'Неформальний діалог',
        'style_dialogue_formal': 'Офіційний діалог',
        'speaking_loading': 'Завантаження...',
        'speaking_mic_denied': 'Доступ до мікрофону заборонено',
        'score_pronunciation': 'Вимова',
        'score_context': 'Точність',
        'score_grammar': 'Граматика',
        'vocab_session_size': 'Розмір сесії слів',
        'vocab_words': 'Слова',
        'vocab_sentences': 'Речення',
        'fc_review_mode': 'Повторення',
        'fc_study_mode': 'Вивчення',
        'fc_study_hint': 'Пробіл: Старт / Стоп • Стрілки: Навігація',
        'fc_session_complete': 'Сесію завершено!',
        'fc_new_session': 'Нова сесія',
        'context': 'Контекст:',
        'go_to_text': 'Перейти до тексту',
        'undo': 'ВІДМІНИТИ',
        'speaking_sentences': 'Переклад',
        'speaking_small_talk': 'Розмова',
        'sentence_removed_fav': 'Речення видалено',
        'text_deleted': 'Текст видалено',
    },
    'eng': {
        'settings': 'Settings',
        'library': 'Library',
        'main': 'Main',
        'logout': 'Logout',
        'generate_new': 'Create Lesson',
        'topic': 'Lesson Topic',
        'level': 'Level',
        'count': 'Sentence count',
        'generate_btn': 'Generate',
        'vocab': 'Vocabulary',
        'voice': 'Voice',
        'back': 'Back',
        'topic_placeholder': 'E.g.: Travel, IT, Sports...',
        'generating': 'Generating...',
        'error_alert': 'Error',
        'show_translation': 'Show translation',
        'hide_translation': 'Hide translation',
        'play_all': 'PLAY ALL',
        'stop': 'STOP',
        'add_translation': '+ TRANSLATE',
        'grammar_tooltip': 'Explain grammar',
        'lesson_vocab': 'LESSON VOCABULARY',
        'empty_vocab_prompt': 'Highlight a word in the text to add a translation.',
        'quiz_tab': 'Quiz',
        'vocab_tab': 'Lesson Vocabulary',
        'check_btn': 'Try',
        'next_btn': 'Next',
        'finish_btn': 'Check',
        'retry_btn': 'Retry',
        'done_btn': 'Done',
        'quiz_completed': 'Quiz Completed!',
        'your_score': 'Your Score',
        'restart_btn': 'Restart',
        'abort_btn': 'Finish',
        'word_added': 'Word added',
        'selection_limited_toast': 'Translation up to 4 words',
        'translation_failed_msg': 'Failed to get translation',
        'audio_failed_msg': 'Failed to generate audio',
        'word_exists': 'Word already in vocabulary',
        'error_generic': 'An error occurred',
        'loading': 'Loading...',
        'word_deleted': 'Word deleted',
        'confirm_delete_word': 'Delete word?',
        'restart_confirm_title': 'Restart Quiz?',
        'confirm_title': 'Confirmation',
        'confirm_delete_text_msg': 'Are you sure you want to delete this text?',
        'btn_delete': 'Delete',
        'restart_confirm_msg': 'Current progress will be lost. Are you sure?',
        'abort_confirm_title': 'Exit Quiz?',
        'abort_confirm_msg': 'Progress will be lost. Exit?',
        'btn_cancel': 'Cancel',
        'exit_btn': 'Exit',
        'my_vocab': 'MY VOCABULARY',
        'save_settings': 'Save',
        'interface_lang': 'Interface Language',
        'my_texts': 'My Texts',
        'read': 'Read',
        'settings_saved': 'Settings saved',
        'style_label': 'Text Style',
        'style_neutral': 'Neutral',
        'style_formal': 'Formal',
        'style_conversational': 'Conversational',
        'style_dialogue_informal': 'Informal Dialogue',
        'style_dialogue_formal': 'Formal Dialogue',
        'speaking_loading': 'Loading...',
        'speaking_mic_denied': 'Mic access denied',
        'score_pronunciation': 'Pronunciation',
        'score_context': 'Accuracy',
        'score_grammar': 'Grammar',
        'vocab_session_size': 'Vocab Session Size',
        'vocab_words': 'Words',
        'vocab_sentences': 'Sentences',
        'fc_review_mode': 'Review',
        'fc_study_mode': 'Study',
        'fc_study_hint': 'Space: Start / Stop • Arrows: Navigation',
        'fc_session_complete': 'Session complete!',
        'fc_new_session': 'New Session',
        'context': 'Context:',
        'go_to_text': 'Go to text',
        'undo': 'UNDO',
        'speaking_sentences': 'Translate',
        'speaking_small_talk': 'Dialogue',
        'sentence_removed_fav': 'Sentence removed',
        'text_deleted': 'Text deleted',
    
    }
};

export const getUI = (lang) => UI_STRINGS[lang] || UI_STRINGS['ukr'];