export const UI_STRINGS = {
    'ukr': {
        'settings': 'Налаштування',
        'library': 'Бібліотека',
        'main': 'Головна',
        'logout': 'Вийти',
        'generate_new': 'Створити Урок',
        'choose_topic': 'Обери тему',
        'your_text': 'Твій текст',
        'your_german_text': 'Твій німецький текст',
        'use_your_german_text': 'Використайте свій німецький текст',
        'create_btn': 'Створити',
        'topic': 'Тема уроку',
        'level': 'Рівень',
        'count': 'Кількість речень',
        'generate_btn': 'Згенерувати',
        'vocab': 'Словник',
        'voice': 'Голос',
        'back': 'Назад',
        'topic_placeholder': 'Наприклад: Подорож, IT, Спорт...',
        'generating': 'Генерація...',
        'error_alert': 'Помилка',
        'show_translation': 'Показати переклад',
        'hide_translation': 'Приховати переклад',
        'play_all': 'ПРОГРАТИ ВСЕ',
        'stop': 'ЗУПИНИТИ',
        'add_translation': '+ ПЕРЕКЛАСТИ',
        'explain_selection': 'ПОЯСНИТИ',
        'explain_failed': 'Не вдалося отримати пояснення',
        'explain_failed_msg': 'Не вдалося отримати пояснення',
        'explain_ready': 'Пояснення додано',
        'explain_single_word_only': 'Пояснення доступне лише для одного слова',
        'explain_nouns': 'Іменники',
        'explain_verbs': 'Дієслова',
        'explain_adj_adv': 'Прикметники / Прислівники',
        'explain_synonyms': 'Синоніми',
        'explain_antonyms': 'Антоніми',
        'explain_no_data': 'Немає даних пояснення',
        'lesson_vocab': 'СЛОВНИК УРОКУ',
        'empty_vocab_prompt': 'Виділіть слово в тексті, щоб додати переклад.',
        'quiz_tab': 'Квіз',
        'vocab_tab': 'Словник уроку',
        'check_btn': 'Спробувати',
        'next_btn': 'Далі',
        'done_btn': 'Готово',
        'finish_btn': 'Перевірити',
        'retry_btn': 'Спробувати ще',
        'quiz_completed': 'Квіз завершено!',
        'restart_btn': 'Спочатку',
        'abort_btn': 'Завершити',
        'word_added': 'Слово додано',
        'selection_limited_toast': 'Переклад не більше 4 слів',
        'translation_failed_msg': 'Не вдалося отримати переклад',
        'audio_failed_msg': 'Не вдалося згенерувати аудіо',
        'word_exists': 'Слово вже є у словнику',
        'error_generic': 'Сталася помилка',
        'loading': 'Завантаження...',
        'word_deleted': 'Слово видалено',
        'confirm_delete_word': 'Видалити слово?',
        'restart_confirm_title': 'Почати спочатку?',
        'confirm_title': 'Підтвердження',
        'confirm_delete_text_msg': 'Ви впевнені, що хочете видалити цей текст?',
        'btn_delete': 'Видалити',
        'restart_confirm_msg': 'Поточний прогрес буде втрачено. Ви впевнені?',
        'abort_confirm_title': 'Завершити квіз?',
        'abort_confirm_msg': 'Прогрес не буде збережено. Вийти?',
        'btn_cancel': 'Скасувати',
        'exit_btn': 'Вийти',
        'my_vocab': 'МІЙ СЛОВНИК',
        'save_settings': 'Зберегти',
        'interface_lang': 'Мова інтерфейсу',
        'my_texts': 'Мої тексти',
        'read': 'Читати',
        'settings_saved': 'Налаштування збережено',
        'style_label': 'Стиль тексту',
        'style_neutral': 'Нейтральний',
        'style_formal': 'Офіційний',
        'style_conversational': 'Розмовний',
        'style_dialogue_informal': 'Неформальний діалог',
        'style_dialogue_formal': 'Офіційний діалог',
        'speaking_loading': 'Завантаження...',
        'speaking_mic_denied': 'Доступ до мікрофону заборонено',
        'score_pronunciation': 'Вимова',
        'score_context': 'Точність',
        'score_grammar': 'Граматика',
        'vocab_session_size': 'Кількість слів для тесту',
        'study_batch_size': 'Кількість слів в режимі вивчення',
        'vocab_words': 'Слова',
        'vocab_sentences': 'Речення',
        'mode_training': 'Тренування',
        'mode_test': 'Тест',
        'fc_review_mode': 'Повторення',
        'fc_study_mode': 'Вивчення',
        'fc_study_hint': 'Пробіл: Старт / Стоп • Стрілки: Навігація',
        'fc_review_hint': 'Пробіл: Старт / Стоп',
        'fc_session_complete': 'Сесію завершено!',
        'study_completed': 'Тренування завершено!',
        'your_score': 'Ваш результат',
        'continue_btn': 'Продовжити',
        'fc_new_session': 'Нова сесія',
        'fc_tap_to_flip': 'Натисніть, щоб перевернути',
        'fc_press_space': 'або пробіл',
        'fc_start_review': 'Почати повторення',
        'fc_hard': 'Не знаю',
        'fc_medium': 'Так собі',
        'fc_easy': 'Знаю',
        'context': 'Контекст:',
        'go_to_text': 'Перейти до тексту',
        'undo': 'ВІДМІНИТИ',
        'speaking_sentences': 'Переклад',
        'speaking_small_talk': 'Розмова',
        'sentence_removed_fav': 'Речення видалено',
        'text_deleted': 'Текст видалено',
        'search': 'Пошук...',
        'error_saving': 'Помилка збереження',
        'error_empty_text': 'Будь ласка, введіть текст',
        'validation_not_german': 'Текст повинен бути німецькою мовою',
        'validation_not_ethical': 'Текст містить неетичний контент',
        'validation_sexual_content': 'Текст містить сексуальний контент',
        'validation_prohibited_topics': 'Текст містить заборонені теми',
        'validation_not_safe': 'Текст не підходить для навчання',
        'validation_error_title': 'Не вдалося створити урок',
        'validation_error_close': 'Закрити',
        'add_custom_word_title': 'Додати нове слово',
        'add_custom_word_placeholder': 'Введіть слово або фразу',
        'add_custom_word_hint': 'Введіть слово або фразу (до 4 слів)',
        'add_custom_word_btn': 'Додати',
        'add_custom_word_btn_label': 'Додати Слово',
        'add_custom_word_adding': 'Додавання...',
        'add_custom_word_max_words': 'Максимум 4 слова',
        'add_custom_word_empty': 'Введіть слово або фразу',
        'add_custom_word_invalid': 'Слово невалідне',
        'add_custom_word_error': 'Помилка при додаванні слова',
        'add_custom_word_success': 'Слово додано успішно',
    },
    'eng': {
        'settings': 'Settings',
        'library': 'Library',
        'main': 'Main',
        'logout': 'Logout',
        'generate_new': 'Create Lesson',
        'choose_topic': 'Choose Topic',
        'your_text': 'Your Text',
        'your_german_text': 'Your German Text',
        'use_your_german_text': 'Use your German text',
        'create_btn': 'Create',
        'topic': 'Lesson Topic',
        'level': 'Level',
        'count': 'Sentence count',
        'generate_btn': 'Generate',
        'vocab': 'Vocabulary',
        'voice': 'Voice',
        'back': 'Back',
        'topic_placeholder': 'E.g.: Travel, IT, Sports...',
        'generating': 'Generating...',
        'error_alert': 'Error',
        'show_translation': 'Show translation',
        'hide_translation': 'Hide translation',
        'play_all': 'PLAY ALL',
        'stop': 'STOP',
        'add_translation': '+ TRANSLATE',
        'explain_selection': 'EXPLAIN',
        'explain_failed': 'Failed to get explanation',
        'explain_failed_msg': 'Failed to get explanation',
        'explain_ready': 'Explanation added',
        'explain_single_word_only': 'Explanation is available for one word only',
        'explain_nouns': 'Nouns',
        'explain_verbs': 'Verbs',
        'explain_adj_adv': 'Adjectives / Adverbs',
        'explain_synonyms': 'Synonyms',
        'explain_antonyms': 'Antonyms',
        'explain_no_data': 'No explanation data',
        'lesson_vocab': 'LESSON VOCABULARY',
        'empty_vocab_prompt': 'Highlight a word in the text to add a translation.',
        'quiz_tab': 'Quiz',
        'vocab_tab': 'Lesson Vocabulary',
        'check_btn': 'Try',
        'next_btn': 'Next',
        'finish_btn': 'Check',
        'retry_btn': 'Retry',
        'done_btn': 'Done',
        'quiz_completed': 'Quiz Completed!',
        'restart_btn': 'Restart',
        'abort_btn': 'Finish',
        'word_added': 'Word added',
        'selection_limited_toast': 'Translation up to 4 words',
        'translation_failed_msg': 'Failed to get translation',
        'audio_failed_msg': 'Failed to generate audio',
        'word_exists': 'Word already in vocabulary',
        'error_generic': 'An error occurred',
        'loading': 'Loading...',
        'word_deleted': 'Word deleted',
        'confirm_delete_word': 'Delete word?',
        'restart_confirm_title': 'Restart Quiz?',
        'confirm_title': 'Confirmation',
        'confirm_delete_text_msg': 'Are you sure you want to delete this text?',
        'btn_delete': 'Delete',
        'restart_confirm_msg': 'Current progress will be lost. Are you sure?',
        'abort_confirm_title': 'Exit Quiz?',
        'abort_confirm_msg': 'Progress will be lost. Exit?',
        'btn_cancel': 'Cancel',
        'exit_btn': 'Exit',
        'my_vocab': 'MY VOCABULARY',
        'save_settings': 'Save',
        'interface_lang': 'Interface Language',
        'my_texts': 'My Texts',
        'read': 'Read',
        'settings_saved': 'Settings saved',
        'style_label': 'Text Style',
        'style_neutral': 'Neutral',
        'style_formal': 'Formal',
        'style_conversational': 'Conversational',
        'style_dialogue_informal': 'Informal Dialogue',
        'style_dialogue_formal': 'Formal Dialogue',
        'speaking_loading': 'Loading...',
        'speaking_mic_denied': 'Mic access denied',
        'score_pronunciation': 'Pronunciation',
        'score_context': 'Accuracy',
        'score_grammar': 'Grammar',
        'vocab_session_size': 'Number of words for test',
        'study_batch_size': 'Number of words in training mode',
        'vocab_words': 'Words',
        'vocab_sentences': 'Sentences',
        'mode_training': 'Training',
        'mode_test': 'Test',
        'fc_tap_to_flip': 'Tap to flip',
        'fc_press_space': 'or press Space',
        'fc_start_review': 'Start Review',
        'fc_hard': 'Hard',
        'fc_medium': 'Medium',
        'fc_easy': 'Easy',
        'fc_review_mode': 'Review',
        'fc_study_mode': 'Study',
        'fc_study_hint': 'Space: Start / Stop • Arrows: Navigation',
        'fc_review_hint': 'Space: Start / Stop',
        'fc_session_complete': 'Session complete!',
        'study_completed': 'Training complete!',
        'your_score': 'Your Score',
        'continue_btn': 'Continue',
        'fc_new_session': 'New Session',
        'context': 'Context:',
        'go_to_text': 'Go to text',
        'undo': 'UNDO',
        'speaking_sentences': 'Translate',
        'speaking_small_talk': 'Dialogue',
        'sentence_removed_fav': 'Sentence removed',
        'text_deleted': 'Text deleted',
        'search': 'Search...',
        'error_saving': 'Error saving',
        'error_empty_text': 'Please enter text',
        'validation_not_german': 'Text must be in German',
        'validation_not_ethical': 'Text contains unethical content',
        'validation_sexual_content': 'Text contains sexual content',
        'validation_prohibited_topics': 'Text contains prohibited topics',
        'validation_not_safe': 'Text is not suitable for learning',
        'validation_error_title': 'Failed adding a text',
        'validation_error_close': 'Close',
        'add_custom_word_title': 'Add New Word',
        'add_custom_word_placeholder': 'Enter a word or phrase',
        'add_custom_word_hint': 'Enter a word or phrase (up to 4 words)',
        'add_custom_word_btn': 'Add',
        'add_custom_word_btn_label': 'Add Word',
        'add_custom_word_adding': 'Adding...',
        'add_custom_word_max_words': 'Maximum 4 words',
        'add_custom_word_empty': 'Please enter a word or phrase',
        'add_custom_word_invalid': 'Word is invalid',
        'add_custom_word_error': 'Error adding word',
        'add_custom_word_success': 'Word added successfully'
    }
};

export const getUI = (lang) => UI_STRINGS[lang] || UI_STRINGS['ukr'];